import os
import base64, hashlib, hmac, secrets
from contextlib import asynccontextmanager
from datetime import datetime, date
import json
import smtplib
from email.message import EmailMessage
from pathlib import Path

from fastapi import Cookie, FastAPI, File, HTTPException, Response, UploadFile, Request, Header
from fastapi.responses import FileResponse, Response as RawResponse, HTMLResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel, Field
from sqlalchemy import create_engine, text
from sqlalchemy.exc import IntegrityError
import httpx

BASE=Path(__file__).resolve().parents[2]
FRONT=BASE/"frontend"
url=os.getenv("DATABASE_URL",f"sqlite:///{BASE/'database'/'lifeos.db'}")
if url.startswith("postgres://"): url="postgresql+psycopg://"+url[11:]
elif url.startswith("postgresql://"): url="postgresql+psycopg://"+url[13:]
engine=create_engine(url,pool_pre_ping=True,connect_args={"check_same_thread":False} if url.startswith("sqlite") else {})
is_pg=url.startswith("postgresql")
ID="INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if is_pg else "INTEGER PRIMARY KEY AUTOINCREMENT"
BINARY="BYTEA" if is_pg else "BLOB"

SCHEMA=[
f"""CREATE TABLE IF NOT EXISTS users(id {ID},username VARCHAR(40) UNIQUE NOT NULL,password_hash TEXT NOT NULL,email VARCHAR(255),plan VARCHAR(20) DEFAULT 'free',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)""",
"""CREATE TABLE IF NOT EXISTS sessions(token VARCHAR(128) PRIMARY KEY,user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)""",
f"""CREATE TABLE IF NOT EXISTS projects(id {ID},name VARCHAR(120) NOT NULL,description TEXT DEFAULT '',color VARCHAR(40) DEFAULT '',user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)""",
f"""CREATE TABLE IF NOT EXISTS tasks(id {ID},title VARCHAR(200) NOT NULL,completed BOOLEAN DEFAULT FALSE,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,due_date VARCHAR(32),user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,project_id INTEGER REFERENCES projects(id) ON DELETE SET NULL,tags TEXT DEFAULT '')""",
f"""CREATE TABLE IF NOT EXISTS notes(id {ID},title VARCHAR(200) NOT NULL,content TEXT DEFAULT '',tags TEXT DEFAULT '',project_id INTEGER REFERENCES projects(id) ON DELETE SET NULL,user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)""",
f"""CREATE TABLE IF NOT EXISTS files(id {ID},name VARCHAR(255) NOT NULL,content_type VARCHAR(150) DEFAULT 'application/octet-stream',data {BINARY} NOT NULL,size INTEGER DEFAULT 0,user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)""",
f"""CREATE TABLE IF NOT EXISTS analytics_events(id {ID},user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,event VARCHAR(120) NOT NULL,path VARCHAR(255),metadata TEXT DEFAULT '',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)""",
f"""CREATE TABLE IF NOT EXISTS notification_preferences(user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,due_task_email BOOLEAN DEFAULT TRUE,marketing_email BOOLEAN DEFAULT FALSE)"""
]
def init_db():
    with engine.begin() as db:
        for s in SCHEMA: db.execute(text(s))
        queries = [
            "ALTER TABLE users ADD COLUMN IF NOT EXISTS email VARCHAR(255)",
            "ALTER TABLE users ADD COLUMN IF NOT EXISTS plan VARCHAR(20) DEFAULT 'free'",
            "ALTER TABLE users ADD COLUMN IF NOT EXISTS "
        ] if is_pg else [
            "ALTER TABLE users ADD COLUMN email VARCHAR(255)",
            "ALTER TABLE users ADD COLUMN plan VARCHAR(20) DEFAULT 'free'",
            "ALTER TABLE users ADD COLUMN "
        ]
        for q in queries:
            try: db.execute(text(q))
            except Exception: pass

def phash(p):
    salt=secrets.token_bytes(16); key=hashlib.scrypt(p.encode(),salt=salt,n=16384,r=8,p=1)
    return base64.b64encode(salt+b"."+key).decode()
def pcheck(p,s):
    try:
        raw=base64.b64decode(s); salt,key=raw.split(b".",1)
        return hmac.compare_digest(key,hashlib.scrypt(p.encode(),salt=salt,n=16384,r=8,p=1))
    except Exception:return False
def tags(s): return ",".join(dict.fromkeys(x.strip() for x in (s or "").split(",") if x.strip()))
def session(uid):
    token=secrets.token_urlsafe(48)
    with engine.begin() as db: db.execute(text("INSERT INTO sessions(token,user_id) VALUES(:t,:u)"),{"t":token,"u":uid})
    return token
def user(cookie):
    if not cookie:return None
    with engine.connect() as db:return db.execute(text("SELECT u.id,u.username,u.created_at FROM users u JOIN sessions s ON s.user_id=u.id WHERE s.token=:t"),{"t":cookie}).mappings().first()
def need(cookie):
    u=user(cookie)
    if not u:raise HTTPException(401,"Please log in.")
    return u
def rows(sql,p={}):
    with engine.connect() as db:return db.execute(text(sql),p).mappings().all()

class Cred(BaseModel):
    username:str=Field(min_length=3,max_length=40); password:str=Field(min_length=8,max_length=128); email:str|None=None
class SettingsIn(BaseModel):
    email:str|None=None; due_task_email:bool=True; marketing_email:bool=False
class TaskIn(BaseModel):
    title:str=Field(min_length=1,max_length=200); due_date:str|None=None; project_id:int|None=None; tags:str=""
class TaskPatch(BaseModel):
    title:str|None=Field(default=None,min_length=1,max_length=200); due_date:str|None=None; project_id:int|None=None; tags:str=""
class ProjectIn(BaseModel):
    name:str=Field(min_length=1,max_length=120); description:str=""; color:str=""
class NoteIn(BaseModel):
    title:str=Field(min_length=1,max_length=200); content:str=""; tags:str=""; project_id:int|None=None

@asynccontextmanager
async def lifespan(app): init_db(); yield
app=FastAPI(title="LifeOS",version="2.0.0",lifespan=lifespan)
app.mount("/css",StaticFiles(directory=FRONT/"css"),name="css"); app.mount("/js",StaticFiles(directory=FRONT/"js"),name="js")

@app.get("/google5874d0f26668ab6b.html")
def google_verification():
    return Response("google-site-verification: google5874d0f26668ab6b.html\\n", media_type="text/html")

@app.get("/")
def home(): return FileResponse(FRONT/"index.html")
@app.get("/health")
def health():
    try:
        with engine.connect() as db: db.execute(text("SELECT 1"))
        return {"status":"ok","project":"lifeos","database":"connected","version":"3.0.0"}
    except Exception: raise HTTPException(503,"Database unavailable")

@app.post("/api/auth/register")
def register(x:Cred,response:Response):
    name=x.username.strip().lower()
    try:
        with engine.begin() as db:
            r=db.execute(text("INSERT INTO users(username,password_hash,email) VALUES(:n,:p,:e) RETURNING id"),{"n":name,"p":phash(x.password),"e":(x.email or "").strip().lower() or None}).first()
            uid=r[0]
    except IntegrityError: raise HTTPException(409,"Username already exists.")
    response.set_cookie("lifeos_session",session(uid),httponly=True,samesite="lax",secure=url.startswith("postgres"),max_age=2592000)
    return {"id":uid,"username":name}

@app.post("/api/auth/login")
def login(x:Cred,response:Response):
    name=x.username.strip().lower()
    with engine.connect() as db:u=db.execute(text("SELECT * FROM users WHERE username=:n"),{"n":name}).mappings().first()
    if not u or not pcheck(x.password,u["password_hash"]):raise HTTPException(401,"Invalid username or password.")
    response.set_cookie("lifeos_session",session(u["id"]),httponly=True,samesite="lax",secure=url.startswith("postgres"),max_age=2592000)
    return {"id":u["id"],"username":u["username"]}

@app.post("/api/auth/logout")
def logout(response:Response,lifeos_session:str|None=Cookie(default=None)):
    if lifeos_session:
        with engine.begin() as db:db.execute(text("DELETE FROM sessions WHERE token=:t"),{"t":lifeos_session})
    response.delete_cookie("lifeos_session");return {"ok":True}
@app.get("/api/auth/me")
def me(lifeos_session:str|None=Cookie(default=None)):return dict(need(lifeos_session))

def send_email(to, subject, body):
    host=os.getenv("SMTP_HOST")
    if not host or not to: return False
    msg=EmailMessage(); msg["From"]=os.getenv("SMTP_FROM",os.getenv("SMTP_USER","LifeOS")); msg["To"]=to; msg["Subject"]=subject; msg.set_content(body)
    with smtplib.SMTP(host,int(os.getenv("SMTP_PORT","587")),timeout=20) as s:
        if os.getenv("SMTP_TLS","1")=="1": s.starttls()
        if os.getenv("SMTP_USER"): s.login(os.getenv("SMTP_USER"),os.getenv("SMTP_PASSWORD",""))
        s.send_message(msg)
    return True

def track(event, uid=None, path=""):
    with engine.begin() as db:
        db.execute(text("INSERT INTO analytics_events(user_id,event,path,metadata) VALUES(:u,:e,:p,'')"),{"u":uid,"e":event[:120],"p":path[:255]})

@app.get("/api/settings")
def get_settings(lifeos_session:str|None=Cookie(default=None)):
    u=need(lifeos_session); pref=rows("SELECT * FROM notification_preferences WHERE user_id=:u",{"u":u["id"]})
    usr=rows("SELECT email FROM users WHERE id=:u",{"u":u["id"]})[0]; p=pref[0] if pref else {"due_task_email":True,"marketing_email":False}
    return {"email":usr["email"],"due_task_email":bool(p["due_task_email"]),"marketing_email":bool(p["marketing_email"])}

@app.patch("/api/settings")
def update_settings(x:SettingsIn,lifeos_session:str|None=Cookie(default=None)):
    u=need(lifeos_session)
    with engine.begin() as db:
        db.execute(text("UPDATE users SET email=:e WHERE id=:u"),{"e":(x.email or "").strip().lower() or None,"u":u["id"]})
        if is_pg:
            db.execute(text("INSERT INTO notification_preferences(user_id,due_task_email,marketing_email) VALUES(:u,:d,:m) ON CONFLICT(user_id) DO UPDATE SET due_task_email=:d,marketing_email=:m"),{"u":u["id"],"d":x.due_task_email,"m":x.marketing_email})
        else:
            db.execute(text("DELETE FROM notification_preferences WHERE user_id=:u"),{"u":u["id"]})
            db.execute(text("INSERT INTO notification_preferences(user_id,due_task_email,marketing_email) VALUES(:u,:d,:m)"),{"u":u["id"],"d":x.due_task_email,"m":x.marketing_email})
    return get_settings(lifeos_session)

@app.post("/api/analytics/event")
def analytics_event(data:dict,lifeos_session:str|None=Cookie(default=None)):
    u=need(lifeos_session); track(str(data.get("event","unknown")),u["id"],str(data.get("path",""))); return {"ok":True}

@app.get("/api/admin/analytics")
def admin_analytics(x_key:str=""):
    key=os.getenv("ADMIN_ANALYTICS_KEY")
    if not key or x_key != key: raise HTTPException(403,"Forbidden")
    return rows("SELECT event,COUNT(*) count FROM analytics_events GROUP BY event ORDER BY count DESC")

@app.get("/api/admin/user-count")
def admin_user_count(lifeos_session:str|None=Cookie(default=None)):
    u=need(lifeos_session)
    if str(u.get("username","")).strip().casefold() != "fawad malik":
        raise HTTPException(403,"Forbidden")
    with engine.connect() as db:
        total=db.execute(text("SELECT COUNT(*) FROM users")).scalar_one()
    return {"users":int(total)}

@app.get("/robots.txt")
def robots():
    base=os.getenv("PUBLIC_BASE_URL","https://lifeos-nqn8-production.up.railway.app").rstrip("/")
    return Response(f"User-agent: *\\nAllow: /\\nSitemap: {base}/sitemap.xml\\n",media_type="text/plain")

@app.get("/sitemap.xml")
def sitemap():
    base=os.getenv("PUBLIC_BASE_URL","https://lifeos-nqn8-production.up.railway.app").rstrip("/")
    urls=[base+"/",base+"/privacy",base+"/terms"]
    xml='<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join(f"<url><loc>{x}</loc></url>" for x in urls)+"</urlset>"
    return Response(xml,media_type="application/xml")

def seo_page(title,heading,body):
    return HTMLResponse(f"""<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title} · LifeOS</title><meta name="description" content="{heading}"></head><body style="font-family:system-ui;max-width:820px;margin:60px auto;padding:24px;line-height:1.7"><a href="/">← LifeOS</a><h1>{heading}</h1>{body}</body></html>""")

@app.get("/privacy")
def privacy_page(): return seo_page("Privacy","LifeOS privacy","<p>LifeOS stores the account and workspace data needed to provide the service. Product analytics are first-party events.</p>")
@app.get("/terms")
def terms_page(): return seo_page("Terms","LifeOS terms","<p>Use LifeOS responsibly and only upload content you are allowed to store. Features may change.</p>")

@app.get("/api/notifications/run")
def run_notifications(secret:str=""):
    if secret != os.getenv("CRON_SECRET",""): raise HTTPException(403,"Forbidden")
    due=rows("""SELECT t.title,u.email FROM tasks t JOIN users u ON u.id=t.user_id LEFT JOIN notification_preferences p ON p.user_id=u.id WHERE t.completed=FALSE AND t.due_date=:d AND u.email IS NOT NULL AND COALESCE(p.due_task_email,TRUE)=TRUE""",{"d":date.today().isoformat()})
    sent=0
    for item in due:
        if send_email(item["email"],"LifeOS task due today",f"You have a LifeOS task due today:\n\n{item['title']}\n\nOpen LifeOS to keep moving."): sent+=1
    return {"matched":len(due),"sent":sent}

@app.get("/api/tasks")
def list_tasks(q:str="",lifeos_session:str|None=Cookie(default=None)):
    u=need(lifeos_session); z=f"%{q}%"
    return rows("SELECT * FROM tasks WHERE user_id=:u AND (title LIKE :z OR tags LIKE :z) ORDER BY completed,due_date,id DESC",{"u":u["id"],"z":z})
@app.post("/api/tasks")
def create_task(x:TaskIn,lifeos_session:str|None=Cookie(default=None)):
    u=need(lifeos_session); title=x.title.strip()
    if x.project_id and not rows("SELECT id FROM projects WHERE id=:p AND user_id=:u",{"p":x.project_id,"u":u["id"]}):raise HTTPException(404,"Project not found.")
    with engine.begin() as db:
        r=db.execute(text("INSERT INTO tasks(title,due_date,project_id,tags,user_id) VALUES(:t,:d,:p,:g,:u) RETURNING *"),{"t":title,"d":x.due_date,"p":x.project_id,"g":tags(x.tags),"u":u["id"]}).mappings().first()
    return dict(r)
@app.patch("/api/tasks/{tid}")
def update_task(tid:int,x:TaskPatch,lifeos_session:str|None=Cookie(default=None)):
    u=need(lifeos_session)
    old=rows("SELECT * FROM tasks WHERE id=:i AND user_id=:u",{"i":tid,"u":u["id"]})
    if not old:raise HTTPException(404,"Task not found.")
    v=x.model_dump(exclude_unset=True); title=(v.get("title") or old[0]["title"]).strip()
    if v.get("project_id") and not rows("SELECT id FROM projects WHERE id=:p AND user_id=:u",{"p":v["project_id"],"u":u["id"]}):raise HTTPException(404,"Project not found.")
    with engine.begin() as db:
        db.execute(text("UPDATE tasks SET title=:t,due_date=:d,project_id=:p,tags=:g WHERE id=:i AND user_id=:u"),{"t":title,"d":v.get("due_date",old[0]["due_date"]),"p":v.get("project_id",old[0]["project_id"]),"g":tags(v.get("tags",old[0]["tags"])),"i":tid,"u":u["id"]})
    return dict(rows("SELECT * FROM tasks WHERE id=:i",{"i":tid})[0])
@app.patch("/api/tasks/{tid}/complete")
def complete_task(tid:int,lifeos_session:str|None=Cookie(default=None)):
    u=need(lifeos_session)
    with engine.begin() as db:r=db.execute(text("UPDATE tasks SET completed=TRUE WHERE id=:i AND user_id=:u"),{"i":tid,"u":u["id"]})
    if not r.rowcount:raise HTTPException(404,"Task not found.")
    return dict(rows("SELECT * FROM tasks WHERE id=:i",{"i":tid})[0])
@app.delete("/api/tasks/{tid}",status_code=204)
def delete_task(tid:int,lifeos_session:str|None=Cookie(default=None)):
    u=need(lifeos_session)
    with engine.begin() as db:r=db.execute(text("DELETE FROM tasks WHERE id=:i AND user_id=:u"),{"i":tid,"u":u["id"]})
    if not r.rowcount:raise HTTPException(404,"Task not found.")

@app.get("/api/projects")
def list_projects(lifeos_session:str|None=Cookie(default=None)):
    u=need(lifeos_session)
    return rows("SELECT p.*,COUNT(t.id) task_count,COALESCE(SUM(CASE WHEN t.completed THEN 1 ELSE 0 END),0) done_count FROM projects p LEFT JOIN tasks t ON t.project_id=p.id WHERE p.user_id=:u GROUP BY p.id ORDER BY p.id DESC",{"u":u["id"]})
@app.post("/api/projects")
def create_project(x:ProjectIn,lifeos_session:str|None=Cookie(default=None)):
    u=need(lifeos_session)
    with engine.begin() as db:r=db.execute(text("INSERT INTO projects(name,description,color,user_id) VALUES(:n,:d,:c,:u) RETURNING id"),{"n":x.name.strip(),"d":x.description,"c":x.color,"u":u["id"]}).first()
    return {"id":r[0],**x.model_dump()}
@app.patch("/api/projects/{pid}")
def update_project(pid:int,x:ProjectIn,lifeos_session:str|None=Cookie(default=None)):
    u=need(lifeos_session)
    with engine.begin() as db:r=db.execute(text("UPDATE projects SET name=:n,description=:d,color=:c WHERE id=:i AND user_id=:u"),{"n":x.name.strip(),"d":x.description,"c":x.color,"i":pid,"u":u["id"]})
    if not r.rowcount:raise HTTPException(404,"Project not found.")
    return {"id":pid,**x.model_dump()}
@app.delete("/api/projects/{pid}",status_code=204)
def delete_project(pid:int,lifeos_session:str|None=Cookie(default=None)):
    u=need(lifeos_session)
    with engine.begin() as db:r=db.execute(text("DELETE FROM projects WHERE id=:i AND user_id=:u"),{"i":pid,"u":u["id"]})
    if not r.rowcount:raise HTTPException(404,"Project not found.")

@app.get("/api/notes")
def list_notes(q:str="",lifeos_session:str|None=Cookie(default=None)):
    u=need(lifeos_session);z=f"%{q}%"
    return rows("SELECT * FROM notes WHERE user_id=:u AND (title LIKE :z OR content LIKE :z OR tags LIKE :z) ORDER BY updated_at DESC,id DESC",{"u":u["id"],"z":z})
@app.post("/api/notes")
def create_note(x:NoteIn,lifeos_session:str|None=Cookie(default=None)):
    u=need(lifeos_session)
    with engine.begin() as db:r=db.execute(text("INSERT INTO notes(title,content,tags,project_id,user_id) VALUES(:t,:c,:g,:p,:u) RETURNING *"),{"t":x.title.strip(),"c":x.content,"g":tags(x.tags),"p":x.project_id,"u":u["id"]}).mappings().first()
    return dict(r)
@app.patch("/api/notes/{nid}")
def update_note(nid:int,x:NoteIn,lifeos_session:str|None=Cookie(default=None)):
    u=need(lifeos_session)
    with engine.begin() as db:r=db.execute(text("UPDATE notes SET title=:t,content=:c,tags=:g,project_id=:p,updated_at=CURRENT_TIMESTAMP WHERE id=:i AND user_id=:u"),{"t":x.title.strip(),"c":x.content,"g":tags(x.tags),"p":x.project_id,"i":nid,"u":u["id"]})
    if not r.rowcount:raise HTTPException(404,"Note not found.")
    return dict(rows("SELECT * FROM notes WHERE id=:i",{"i":nid})[0])
@app.delete("/api/notes/{nid}",status_code=204)
def delete_note(nid:int,lifeos_session:str|None=Cookie(default=None)):
    u=need(lifeos_session)
    with engine.begin() as db:r=db.execute(text("DELETE FROM notes WHERE id=:i AND user_id=:u"),{"i":nid,"u":u["id"]})
    if not r.rowcount:raise HTTPException(404,"Note not found.")

@app.get("/api/dashboard/stats")
def stats(lifeos_session:str|None=Cookie(default=None)):
    u=need(lifeos_session)
    a=rows("SELECT COUNT(*) total,COALESCE(SUM(CASE WHEN completed THEN 1 ELSE 0 END),0) done FROM tasks WHERE user_id=:u",{"u":u["id"]})[0]
    return {"tasks":a["total"],"completed_tasks":a["done"],"projects":rows("SELECT COUNT(*) n FROM projects WHERE user_id=:u",{"u":u["id"]})[0]["n"],"notes":rows("SELECT COUNT(*) n FROM notes WHERE user_id=:u",{"u":u["id"]})[0]["n"],"files":rows("SELECT COUNT(*) n FROM files WHERE user_id=:u",{"u":u["id"]})[0]["n"]}

@app.get("/api/search")
def search(q:str,lifeos_session:str|None=Cookie(default=None)):
    u=need(lifeos_session);z=f"%{q}%"
    a=rows("SELECT id,title,'task' type FROM tasks WHERE user_id=:u AND (title LIKE :z OR tags LIKE :z) LIMIT 20",{"u":u["id"],"z":z})
    b=rows("SELECT id,name title,'project' type FROM projects WHERE user_id=:u AND (name LIKE :z OR description LIKE :z) LIMIT 20",{"u":u["id"],"z":z})
    c=rows("SELECT id,title,'note' type FROM notes WHERE user_id=:u AND (title LIKE :z OR content LIKE :z OR tags LIKE :z) LIMIT 20",{"u":u["id"],"z":z})
    return [*a,*b,*c]

@app.get("/api/files")
def list_files(lifeos_session:str|None=Cookie(default=None)):
    u=need(lifeos_session);return rows("SELECT id,name,content_type,size,created_at FROM files WHERE user_id=:u ORDER BY id DESC",{"u":u["id"]})
@app.post("/api/files")
async def upload_file(file:UploadFile=File(...),lifeos_session:str|None=Cookie(default=None)):
    u=need(lifeos_session);data=await file.read()
    if len(data)>10*1024*1024:raise HTTPException(413,"Files are limited to 10 MB.")
    name=Path(file.filename or "file").name
    with engine.begin() as db:r=db.execute(text("INSERT INTO files(name,content_type,data,size,user_id) VALUES(:n,:c,:d,:s,:u) RETURNING id"),{"n":name,"c":file.content_type or "application/octet-stream","d":data,"s":len(data),"u":u["id"]}).first()
    return {"id":r[0],"name":name,"size":len(data)}
@app.get("/api/files/{fid}")
def get_file(fid:int,lifeos_session:str|None=Cookie(default=None)):
    u=need(lifeos_session);r=rows("SELECT * FROM files WHERE id=:i AND user_id=:u",{"i":fid,"u":u["id"]})
    if not r:raise HTTPException(404,"File not found.")
    x=r[0];return RawResponse(content=x["data"],media_type=x["content_type"],headers={"Content-Disposition":f'attachment; filename="{x["name"].replace(chr(34),"")}"'})
@app.delete("/api/files/{fid}",status_code=204)
def delete_file(fid:int,lifeos_session:str|None=Cookie(default=None)):
    u=need(lifeos_session)
    with engine.begin() as db:r=db.execute(text("DELETE FROM files WHERE id=:i AND user_id=:u"),{"i":fid,"u":u["id"]})
    if not r.rowcount:raise HTTPException(404,"File not found.")
